In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [96]:
def a⃩b(a,b):
    stock=np.array([a+b,a-b,a*b,a/b])
    return stock

def a⃩⃩b(a,b,c):
    stock=a⃩b(a,b)
    stock=a⃩b(stock,c)
    return stock

def a⃩⃩⃩b(a,b,c,d):
    stock=a⃩⃩b(a,b,c)
    stock=stock=a⃩b(stock,d)
    return stock

def oper(a):
    if a==0:
        return '+'
    elif a==1:
        return '-'
    elif a==2:
        return '*'
    else:
        return '/'

# 湊24
### 功能:給定4個整數，以加減乘除湊出24
### 靈感來源: 包種茶應數系攤位小遊戲
#### 主要思路:多維array
#### 備注:(a+b)*(c+d) 或 a/(b+c+d)... 暫不可解

In [132]:
egg = input('>>').split(',')
egg=list(map(int,egg))
ww=1
uu=0
while ww!=4:
    egg=[egg[1],egg[2],egg[3],egg[0]]
    p=a⃩⃩⃩b(egg[0],egg[1],egg[2],egg[3])
    k=np.where(p==24)
    for i in range(len(k[0])):
        print('(('+ str(egg[0]) + oper(k[2][i]) +str(egg[1]) +')' + oper(k[1][i]) +str(egg[2]) + ')'+ oper(k[0][i]) + str(egg[3]) +'=24\n')
    if len(k[0])==0:
        uu=uu+1
    ww=ww+1
if uu!=0:
    print('無解')

>>3,4,7,10
((4+7)+10)+3=24

((7+10)+3)+4=24

((10+3)+4)+7=24



In [112]:
egg = input('>>').split(',')
egg=list(map(int,egg))

>>1,2,3,4


In [52]:
l1= np.array(range(5))
print(a⃩b(l1,2))

[[ 2.   3.   4.   5.   6. ]
 [-2.  -1.   0.   1.   2. ]
 [ 0.   2.   4.   6.   8. ]
 [ 0.   0.5  1.   1.5  2. ]]


In [53]:
l1= np.array(range(5))
l2=[]
np.append(l2,l1/2)

array([0. , 0.5, 1. , 1.5, 2. ])

In [58]:
print(a⃩b(1,2))

[ 3.  -1.   2.   0.5]


In [74]:
print(np.around(a⃩⃩⃩b(6,6,6,6),0))

[[[ 2.400e+01  1.200e+01  4.800e+01  1.300e+01]
  [ 1.200e+01  0.000e+00  3.600e+01  1.000e+00]
  [ 7.800e+01  6.000e+00  2.220e+02  1.200e+01]
  [ 8.000e+00  6.000e+00  1.200e+01  6.000e+00]]

 [[ 1.200e+01  0.000e+00  3.600e+01  1.000e+00]
  [ 0.000e+00 -1.200e+01  2.400e+01 -1.100e+01]
  [ 6.600e+01 -6.000e+00  2.100e+02  0.000e+00]
  [-4.000e+00 -6.000e+00  0.000e+00 -6.000e+00]]

 [[ 1.080e+02  3.600e+01  2.520e+02  4.200e+01]
  [ 3.600e+01 -3.600e+01  1.800e+02 -3.000e+01]
  [ 4.320e+02  0.000e+00  1.296e+03  3.600e+01]
  [ 1.200e+01  0.000e+00  3.600e+01  1.000e+00]]

 [[ 3.000e+00  1.000e+00  7.000e+00  1.000e+00]
  [ 1.000e+00 -1.000e+00  5.000e+00 -1.000e+00]
  [ 1.200e+01  0.000e+00  3.600e+01  1.000e+00]
  [ 0.000e+00  0.000e+00  1.000e+00  0.000e+00]]]


In [75]:
np.around(a⃩⃩⃩b(6,6,6,6),0)

array([[[ 2.400e+01,  1.200e+01,  4.800e+01,  1.300e+01],
        [ 1.200e+01,  0.000e+00,  3.600e+01,  1.000e+00],
        [ 7.800e+01,  6.000e+00,  2.220e+02,  1.200e+01],
        [ 8.000e+00,  6.000e+00,  1.200e+01,  6.000e+00]],

       [[ 1.200e+01,  0.000e+00,  3.600e+01,  1.000e+00],
        [ 0.000e+00, -1.200e+01,  2.400e+01, -1.100e+01],
        [ 6.600e+01, -6.000e+00,  2.100e+02,  0.000e+00],
        [-4.000e+00, -6.000e+00,  0.000e+00, -6.000e+00]],

       [[ 1.080e+02,  3.600e+01,  2.520e+02,  4.200e+01],
        [ 3.600e+01, -3.600e+01,  1.800e+02, -3.000e+01],
        [ 4.320e+02,  0.000e+00,  1.296e+03,  3.600e+01],
        [ 1.200e+01,  0.000e+00,  3.600e+01,  1.000e+00]],

       [[ 3.000e+00,  1.000e+00,  7.000e+00,  1.000e+00],
        [ 1.000e+00, -1.000e+00,  5.000e+00, -1.000e+00],
        [ 1.200e+01,  0.000e+00,  3.600e+01,  1.000e+00],
        [ 0.000e+00,  0.000e+00,  1.000e+00,  0.000e+00]]])

In [89]:
np.where(a⃩⃩⃩b(6,6,6,6)==24)

(array([0, 1], dtype=int64),
 array([0, 1], dtype=int64),
 array([0, 2], dtype=int64))

In [105]:
k=np.where(a⃩⃩⃩b(6,6,6,6)==24)

In [107]:
k[0]

array([0, 1], dtype=int64)

In [104]:
len(k[0])

2

In [110]:
for i in range(len(k[0])):
    print(str(egg[0]) + oper(k[2][i]) +str(egg[1]) + oper(k[1][i]) +str(egg[2]) + oper(k[0][i]) + str(egg[3]) +'=24\n' )

6+6+6+6=24

6*6-6-6=24



In [116]:
egg=[egg[1],egg[2],egg[3],egg[0]]
print(egg)

[1, 2, 3, 4]


In [129]:
len(k[0])

0